defmodule Yex.StickyIndexTextItemsTest do
  use ExUnit.Case, async: true
  alias Yex.{Doc, StickyIndex, XmlElement, XmlFragment, XmlTextPrelim}

  # Cross-runtime fixture generated by Yjs 13.6.32, UTF-16 coordinates.
  # SHA256 a0efd05ceb97f6503be62f5b661f0abbdb2d97de22347d2f4734764da99b4e96.
  @fixture Path.expand("fixtures/text-items-v1.json", __DIR__)

  test "batch positions match Yjs live and deleted UTF-16 identities" do
    cases = decode_json!(File.read!(@fixture))["cases"]

    for scenario <- Enum.take(cases, 3) do
      doc = load(scenario)

      leaf =
        doc |> Doc.get_xml_fragment("default") |> XmlFragment.fetch!(0) |> XmlElement.fetch!(1)

      [run] = scenario["selection"]["runs"]
      {:ok, [positions]} = StickyIndex.resolve_text_items(leaf, [run(run)])
      actual = for %{status: :live, index: index} <- positions, do: index

      expected =
        for segment <- scenario["expected"]["segments"],
            index <- segment["index"]..(segment["index"] + segment["length"] - 1),
            do: index

      assert actual == expected

      assert Enum.count(positions, &(&1.status == :collapsed)) ==
               scenario["expected"]["collapsedUnits"]
    end
  end

  test "actual branch identity rejects forged type claims including collapsed items" do
    scenario = decode_json!(File.read!(@fixture))["cases"] |> Enum.at(2)
    doc = load(scenario)

    wrong =
      doc |> Doc.get_xml_fragment("default") |> XmlFragment.fetch!(0) |> XmlElement.fetch!(0)

    [claimed] = scenario["selection"]["runs"]
    {:ok, [positions]} = StickyIndex.resolve_text_items(wrong, [run(claimed)])
    assert Enum.all?(positions, &(&1 == %{status: :wrong_type, index: nil}))
  end

  test "missing and garbage-collected identities do not become live offsets" do
    scenario = decode_json!(File.read!(@fixture))["cases"] |> List.last()
    doc = load(scenario)
    root = Doc.get_xml_fragment(doc, "default")
    :ok = XmlFragment.push(root, XmlTextPrelim.from("unrelated"))
    leaf = XmlFragment.fetch!(root, 0)
    [claimed] = scenario["selection"]["runs"]
    {:ok, [positions]} = StickyIndex.resolve_text_items(leaf, [run(claimed)])
    assert Enum.all?(positions, &(&1 == %{status: :unavailable, index: nil}))
    assert {:ok, [[%{status: :unavailable, index: nil}]]} =
      StickyIndex.resolve_text_items(leaf, [%{client: 999, clock: 4_294_967_295, count: 1}])
  end

  test "batch runs share an existing transaction and do not mutate document state" do
    scenario = decode_json!(File.read!(@fixture))["cases"] |> hd()
    doc = load(scenario)
    leaf = doc |> Doc.get_xml_fragment("default") |> XmlFragment.fetch!(0) |> XmlElement.fetch!(1)
    [claimed] = scenario["selection"]["runs"]
    {:ok, before} = Yex.encode_state_as_update(doc)

    Doc.transaction(doc, fn ->
      {:ok, [positions, again]} =
        StickyIndex.resolve_text_items(leaf, [run(claimed), run(claimed)])

      assert positions == again
    end)

    assert Yex.encode_state_as_update(doc) == {:ok, before}
  end

  test "bounded inputs and explicit UTF-16 prevent ambiguous coordinate use" do
    doc = Doc.new()
    root = Doc.get_xml_fragment(doc, "default")
    :ok = XmlFragment.push(root, XmlTextPrelim.from("abc"))
    leaf = XmlFragment.fetch!(root, 0)
    assert {:error, :utf16_required} = StickyIndex.resolve_text_items(leaf, [])
    utf16 = Doc.with_options(%Doc.Options{offset_kind: :utf16})
    root = Doc.get_xml_fragment(utf16, "default")
    :ok = XmlFragment.push(root, XmlTextPrelim.from("abc"))
    leaf = XmlFragment.fetch!(root, 0)

    assert {:error, :selection_limit} =
             StickyIndex.resolve_text_items(leaf, [
               %{client: 1, clock: 0, count: 131_072},
               %{client: 1, clock: 0, count: 1}
             ])

    assert {:error, :selection_limit} =
             StickyIndex.resolve_text_items(
               leaf,
               List.duplicate(%{client: 1, clock: 0, count: 1}, 4097)
             )

    assert_raise ArgumentError, fn ->
      StickyIndex.resolve_text_items(leaf, [%{client: 1, clock: 4_294_967_295, count: 2}])
    end

    assert_raise ArgumentError, fn ->
      Yex.Nif.sticky_index_resolve_text_items(leaf, nil, [
        %{client: 1, clock: 0, count: 1} | :invalid_tail
      ])
    end
  end

  test "redo identity is reported explicitly instead of transferring exact item ownership" do
    doc = Doc.with_options(%Doc.Options{offset_kind: :utf16})
    root = Doc.get_xml_fragment(doc, "default")
    :ok = XmlFragment.push(root, XmlTextPrelim.from(""))
    leaf = XmlFragment.fetch!(root, 0)
    {:ok, undo} = Yex.UndoManager.new(doc, leaf)
    :ok = Yex.XmlText.insert(leaf, 0, "a")

    %{"item" => %{"client" => client, "clock" => clock}} =
      StickyIndex.new(leaf, 0, :after) |> StickyIndex.to_json() |> decode_json!()

    :ok = Yex.UndoManager.undo(undo)
    :ok = Yex.UndoManager.redo(undo)

    assert {:ok, [[%{status: :collapsed, index: index}]]} =
             StickyIndex.resolve_text_items(leaf, [%{client: client, clock: clock, count: 1}])

    assert is_integer(index)
  end

  defp run(%{"item" => item, "count" => count}),
    do: %{client: item["client"], clock: item["clock"], count: count}

  defp load(scenario) do
    doc = Doc.with_options(%Doc.Options{offset_kind: :utf16})
    :ok = Yex.apply_update(doc, Base.decode64!(scenario["update"]))
    doc
  end

  defp decode_json!(json) do
    if Code.ensure_loaded?(Jason), do: Jason.decode!(json), else: :json.decode(json)
  end
end
